### PR TITLE
Fixes for issues #25 and #30

### PR DESCRIPTION
**Pull request by richbrat**

### CODE REVIEW

**Comment by richbrat** [comment]
Sorry for bumping this but i'm about to release a theme which is dependent on this plugin, without this PR some functionality in my theme is useless. (I can of course write some fix in my theme but it seems unnecessary since this is an actual bug in the plugin)

**Comment by codebykat** [comment]
Hi @richbrat, when are you releasing your theme? I am so behind on life :sob:

**Comment by richbrat** [comment]
Would be nice to have something working in about three weeks, but I'm also behind on life (and terrible at meeting deadlines) so we'll see. :) Thanks Kat!

**Comment by codebykat** [comment]
I will try to carve out some time for it! Thanks for the nudge, it helps to know people are still using this. :)

**Comment by codebykat** [comment]
Ooookay working on this finally! Whee! Augh!

**Comment by richbrat** [comment]
Sweet!

**Pull request merged**
